### ISSUE TITLE
DCPU-B Support

### ISSUE THREAD

**Issue by paultech** [paultech/DASM#12]
Wanting to support - https://github.com/Blecki/DCPUB for a higher level language to help bootstrap new players to programming.

Currently the helloworld (output http://hastebin.com/exasivukag.avrasm) example produces the following errors from DASM:

Loading helloworld.dasm
Error: Opcode not found: "HELLOWORLD!
Error: Could not evaluate expression:0XC0X480X650X6C0X6C0X6F0X200X770X6F0X720X6C0X640X21
Error: Could not evaluate expression:0X73490XF615
Error: Could not evaluate expression:0X30CF0X7406
Error: Could not evaluate expression:0X00X00X00X0

**Comment by paultech** [comment]
Appears the 'Opcode not found' is due to comment handling - Removing comments fixes that error. 

The remaining errors are due to space separated DAT lines vs comma separated Adding commas resulted in successful build.

Fixes - 
TC side - Fix parsing of comments to not get out of scope with quotation marks.
DCPUB Side - Produce comma separated DAT lines . Should we fork the repo? I assume so

**Comment by interfect** [comment]
Is there a problem with supporting space-separated DAT lines? It's usually
a good idea to be liberal in what you accept.

**Comment by paultech** [comment]
interfect - I think I prefer having just one officially supported method for DAT lines that way tutorials and documentation writing in the future is consistent. DASM could be liberal in accepting if others see it wise.

**Comment by interfect** [comment]
In that case it might be good to try and get the needed changes up into the
mainline DCPU-B repo, if it's still active. What assembler are they using?

**Comment by paultech** [comment]
The author of DCPUB @Blecki is quite involved in the IRC channel and updating the compiler to meet the needs of TC. We can ask him when in IRC if he's willing to change output of DAT lines or submit a issue to his repo. @ https://github.com/Blecki/DCPUB

**Comment by Blecki** [comment]
@interfect , there is not assembly in DCPUB. It has an internal intermediate format and translates that directly to binary. 

So what is the format you need? I prefer without commas, but it's a trivial change. Will it choke on a trailing comma?
