### ISSUE TITLE
.define doesn't work: "Insufficient operands"

### ISSUE THREAD

**Issue by azertyfun** [paultech/DASM#15]
The following code doesn't compile:

```
.define test A

set test, 5
:end set PC, end
```

Here is the output:

```
./dasm test_define.dasm test_define.bin
Loading test_define.dasm
Error: Insufficient operands: .define test A
Error: Could not evaluate expression:TEST
```

Environment: Archlinux x64 4.4.0-4, Intel i7 4790K, 12 GB RAM

Compiling BareBonesOS doesn't work either:
```
./dasm bbos/bbos.asm bbos.bin
Loading bbos/bbos.asm
Loading bbos.inc.asm
Loading video.asm
Loading drives.asm
Loading keyboard.asm
Loading rtc.asm
Loading comms.asm
Error: Insufficient operands: .define VERSION 0x0100
Error: Insufficient operands: .define RUN_AT  0xF000
Error: Insufficient operands: .define LEM_ID  0x7349f615
Error: Insufficient operands: .define LEM_VER 0x1802
Error: Insufficient operands: .define LEM_MFR 0x1c6c8b36
Error: Insufficient operands: .define LEM_WID 32
Error: Insufficient operands: .define LEM_HGT 12
Error: Insufficient operands: .define VRAM_SIZE   384 ; LEM_WID * LEM_HGT
Error: Insufficient operands: .define MAX_DRIVES  8
Error: Insufficient operands: .define COMMS_IRQ   0x47E0
Error: Insufficient operands: .define HID_CLASS           3
Error: Insufficient operands: .define KEYBOARD_SUBCLASS   0
Error: Insufficient operands: .define COMMS_CLASS         0xE
Error: Insufficient operands: .define PARALLEL_SUBCLASS   0
Error: RFI opcode requires an operand
Error: RFI opcode requires an operand
Error: Could not evaluate expression:BBOSINFO_SIZE
Error: Could not evaluate expression:MAX_DRIVES
Error: Could not evaluate expression:RUN_AT
Error: Could not evaluate expression:VRAM_SIZE
Error: Could not evaluate expression:RUN_AT
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:COMMS_IRQ
Error: Could not evaluate expression:COMMS_NOTIFY
Error: Could not evaluate expression:VIDEO_IRQ
Error: Could not evaluate expression:DRIVE_IRQ
Error: Could not evaluate expression:KEYBOARD_IRQ
Error: Could not evaluate expression:RTC_IRQ
Error: Could not evaluate expression:VERSION
Error: Could not evaluate expression:COMMS_CLASS
Error: Could not evaluate expression:PARALLEL_SUBCLASS
Error: Could not evaluate expression:HID_CLASS
Error: Could not evaluate expression:KEYBOARD_SUBCLASS
Error: Could not evaluate expression:LEM_ID
Error: Could not evaluate expression:LEM_ID
Error: Could not evaluate expression:LEM_VER
Error: Could not evaluate expression:LEM_MFR
Error: Could not evaluate expression:LEM_MFR
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:BBOS_IRQ_MAGIC
Error: Could not evaluate expression:MAX_DRIVES
Error: Could not evaluate expression:LEM_WID
Error: Could not evaluate expression:BBOS_VERSION
Error: Could not evaluate expression:VRAM_SIZE
Error: Could not evaluate expression:BBOS_START_ADDR
Error: Could not evaluate expression:BBOS_END_ADDR
Error: Could not evaluate expression:BBOS_INT_HANDLER
Error: Could not evaluate expression:BBOS_API_HANDLER
```
However, manually replacing doing the job of the preprocessor works fine.

**Comment by azertyfun** [comment]
Further information:

* For the first bit of code `final_split_list` contains only one string: `" test A"`.
* If you replace `.define test A` with `.define test, A` the parser does some weird stuff. The following code:
```
.define TEST, A 

set B, 3
set TEST, 5
:end set PC, end
```
will generate the following output:
```
./dasm test_define.dasm test_define.bin
Loading test_define.dasm
Error: Could not evaluate expression:A
Error: Could not evaluate expression: B
Error: Could not evaluate expression: PC
```

All of it seems related to commit 0cacd51.

**Comment by azertyfun** [comment]
Alright, so if I checkout 6a48201, the .define doesn't work but the error message is different:
```
/dasm test_define.dasm test_define.bin
Loading test_define.dasm
Error: Could not evaluate expression:A
```
Looks like defines have been broken for a long time...

**Comment by MadMockers** [comment]
I'm not sure if defining something as a register is expected to work.

https://github.com/paultech/DASM/commit/6a48201588cb2e3b467c5c6d6efdba4d65850f3d is able to assemble BBOS, https://github.com/paultech/DASM/commit/0cacd5164b7acde3c7cffb4a4a135ac11ad812b6 is not.

**Comment by azertyfun** [comment]
Isn't define considered a preprocessor directive? It should just replace any occurence in the code, shouldn't it?

**Comment by MadMockers** [comment]
It's not a real preprocessor. The defines are evaluated on the same pass as
the parsing. After it has identified a define, I believe it expects a
constant value, hence why your error is 'could not evaluate expression: A'.

**Comment by azertyfun** [comment]
Why is that? Is there a specific reason? All compilers and assemblers I can think of do it the other way...

**Comment by paultech** [comment]
The game itself has a preprocessor running for #include it should also handle #define/.define for a proper pre-pass - Should the preprocessor be built into DAsm as a first stage or separate code base?

**Comment by alfie275** [comment]
"define" is used to define constants, which can always be evaluated straight to numbers, and is done this way for reasons concerning label positioning. Basically, defines get evaluated before chunk-ordering, whereas label values get evaluated afterwards (as the label values depend on chunk-positions).

But yeah, it expects something of the form ".define constant, value".
Perhaps this should be rename "constant" or something? 

We do currently have a macro system that might be useable for similar things, except that's called when it can't find the opcode and is more for higher level code stuff (eg "macro SUM = ADD %0, %1 %n ADD %0, %2" to add three numbers), we could maybe have this be called during argument parsing if it can't evaluate it? As a workaround if you really need it (and you can later find-replace when we have the functionality in), instead of ".define test, A" then "set test, 5", you could do "macro set.test = set A, %0" and then "set.test 5".

I'll look into the best way to handle this without breaking any existing compatibility - I think perhaps simply having macros be evaluated in argument parsing, and then having .define auto-generate macros when it is unable to evaluate to a constant might work quite well all around.

The "SET PC, end" should work - try moving it onto a line seperate from the label.

**Comment by alfie275** [comment]
Ok, I've implemented define auto-macroing and macro use in argument parsing, so (as soon as the pull request is granted), you will be able to do:

DEF MY_REGISTER, A
SET MY_REGISTER, 5

and it will assemble to the correct code, so I'm gonna mark this as closed.
