### ISSUE TITLE
 optimization for [A + 0]

### ISSUE THREAD

**Issue by orlof** [paultech/DASM#22]
Sorry to be nitpicking, but I was curious why dasm still produced 0.4% longer binaries. 
It still doesn't optimize literal offset 0:

SET a, [a + 0]
0x4001 0x0000 vs 0x2001

This case is relevant in my code, because I have data structures where offset for each element is defined as #define directive for code readability. e.g.

.define EXPONENT, 0
.define MANTISSA, 1
set b, float
set a, [b + EXPONENT]
:float DAT 0x8000, 0x8000

(edited to fix the define syntax)

**Comment by orlof** [comment]
Hmm, now that I think of it... Someone might be doing "self-modifying" code that relies on the two word version of the instruction. He might be specifying the +0 just to ensure that.

Perhaps this optimization is not such a great idea after all - or it should be enabled with some compiler flags.

**Comment by NateBrune** [comment]
I like this modification. I use +0 frequently. It is good for readablity as you said. If some code is relying on a bug, lets nip the bug right now so code in the future doesnt rely on it.

**Comment by interfect** [comment]
It might be smart to make all these optimizations controllable with flags
or pragmas or something, so that the one place you really need to generate
a 0x4001 0x0000 you can still have it.

**Comment by alfie275** [comment]
I don't know which DCPU spec you're looking at, but the 1.7 spec (which DCPU-TC spec is based on) does not have provision for putting the register offset in the instruction, only when setting it to a literal -1 to 30:
"0x20-0x3f | literal value 0xffff-0x1e (-1..30) (literal) (only for a)"

Eg, 
"SET A, 1" assembles to "0x8801" whereas "SET A, 64" assembles to "0x7c01 0x0040" - The first is a word shorter.
But "SET A, [A+1]" assembles to "0x4001 0x0001" and "SET A, [A+64]" assembles to "0x4001 0x0040" - They both take two words.

**Comment by alfie275** [comment]
Ah ok, I see what you mean now. I will see about adding this as a flag controllable thing.

**Comment by paultech** [comment]
I may of been premature in closing this issue but this repo is now outdated. Do we need to carry this discussion over?
