### ISSUE TITLE
Freezes when compiling current build of DCPU-BASIC

### ISSUE THREAD

**Issue by unbibium** [paultech/DASM#23]
To reproduce, clone dcpu-cbmbasic at [tag dasm-issue-4](https://github.com/unbibium/dcpu-cbmbasic/tree/dasm-issue-4).  Compile main.dasm16.  It will freeze after "Loading io.dasm16".

**Comment by paultech** [comment]
Hi @unbibium - I gave you a bad link over twitter. This is my personal slgithly outdated copy of the repo. We've moved over to - https://github.com/techcompliant/DASM. We are tracking this issue @ https://github.com/techcompliant/DASM/issues/3

**Comment by paultech** [comment]
Added a readme to this repo pointing to the correct one. Sorry about that!

**Comment by paultech** [comment]
I can't @unbibium over on the new issue but reading over the code it looks like our FILL mnemonics are backwards to you? Fill(value,amount) on our end.
